export const APP_CONSTANTS = {
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  DEFAULT_SORT_ORDER: 'DESC',
  API_VERSION: 'v1',
};

export const TICKET_CONSTANTS = {
  AUTO_ASSIGN_DELAY_MS: 3000,
  MAX_TASKS_PER_WORKER: 10,
};

export const WORKSPACE_CONSTANTS = {
  MAX_MEMBERS: 100,
};

export const CUSTOMER_HIERARCHY_CONSTANTS = {
  MAX_LEVEL: 5,
};

export const MESSAGE_CONSTANTS = {
  MAX_BROADCAST_RECIPIENTS: 1000,
};
